import type { PlatformerConfig } from './types';

export const defaultPlatformerConfig: PlatformerConfig = {
  populationSize: 80,
  steps: 160,
  mutationRate: 0.18,
  mutationStdDev: 0.35,
  crossoverRate: 0.75,
  eliteCount: 4,
  dt: 0.16,
  maxSpeed: 15,
  maxAccel: 18,
  airAccel: 6,
  friction: 0.92,
  jumpVelocity: 9.2,
  gravity: 24,
  directionCost: 0.12,
  momentumBuildRate: 1.1,
  momentumDecay: 0.6,
  momentumJumpBoost: 0.9,
  momentumMax: 4.2,
  strafeThreshold: 0.35,
};

export const fastConfig: Partial<PlatformerConfig> = {
  populationSize: 60,
  steps: 120,
  mutationRate: 0.22,
  mutationStdDev: 0.4,
  eliteCount: 2,
  maxAccel: 16,
  airAccel: 5,
  friction: 0.9,
  directionCost: 0.16,
  jumpVelocity: 9,
  momentumBuildRate: 1,
  momentumDecay: 0.65,
  momentumJumpBoost: 0.95,
  momentumMax: 4,
  strafeThreshold: 0.35,
};

export const exploreConfig: Partial<PlatformerConfig> = {
  populationSize: 120,
  steps: 200,
  mutationRate: 0.16,
  mutationStdDev: 0.3,
  eliteCount: 6,
  maxAccel: 20,
  airAccel: 7,
  friction: 0.94,
  directionCost: 0.11,
  jumpVelocity: 9.4,
  momentumBuildRate: 1.2,
  momentumDecay: 0.55,
  momentumJumpBoost: 0.88,
  momentumMax: 4.6,
  strafeThreshold: 0.32,
};
